// Auto-generated by build_website_data.py
const COMPETITION_DATA = {
  "last_updated": "2026-03-10 22:11:16",
  "teams": {
    "Mandalorian": {
      "total_distance": 566.34,
      "members": 10,
      "active_members": 8,
      "name": "Mandalorian",
      "avg_distance": 56.63
    },
    "IT System": {
      "total_distance": 631.45,
      "members": 10,
      "active_members": 9,
      "name": "IT System",
      "avg_distance": 63.14
    }
  },
  "roster": [
    {
      "nickname": "Gio",
      "thai_name": "โจ",
      "team": "Mandalorian",
      "total_distance": 326.96,
      "active_days": 49,
      "image_count": 65,
      "recent_images": [
        "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-09_1.jpg",
        "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-09.jpg",
        "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-07_1.jpg",
        "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-07.jpg",
        "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-05_1.jpg"
      ],
      "stats_details": {
        "run_dist": 299.83000000000004,
        "walk_dist": 55.08,
        "run_count": 51,
        "walk_count": 15,
        "total_sessions": 66,
        "best_pace": 431,
        "best_pace_activity": "5.5km Easy Run",
        "best_pace_date": "2026-03-09",
        "longest_run_dist": 10.79,
        "longest_run_activity": "Tuesday Night Run",
        "longest_run_date": "2026-01-06"
      }
    },
    {
      "nickname": "Jojo",
      "thai_name": "โจโจ้",
      "team": "IT System",
      "total_distance": 192.78,
      "active_days": 37,
      "image_count": 37,
      "recent_images": [
        "../member_results/ITSystem-6_Jojo (โจโจ้)/running-pics/jojo-2026-mar-05.jpg",
        "../member_results/ITSystem-6_Jojo (โจโจ้)/running-pics/jojo-2026-mar-04.jpg",
        "../member_results/ITSystem-6_Jojo (โจโจ้)/running-pics/jojo-2026-mar-02.jpg",
        "../member_results/ITSystem-6_Jojo (โจโจ้)/running-pics/jojo-2026-mar-01.jpg",
        "../member_results/ITSystem-6_Jojo (โจโจ้)/running-pics/jojo-2026-jan-31.jpg"
      ],
      "stats_details": {
        "run_dist": 109.25000000000001,
        "walk_dist": 83.53,
        "run_count": 12,
        "walk_count": 25,
        "total_sessions": 37,
        "best_pace": 387,
        "best_pace_activity": "Outdoor Run",
        "best_pace_date": "2026-03-05",
        "longest_run_dist": 10.04,
        "longest_run_activity": "Outdoor Run",
        "longest_run_date": "2026-01-08"
      }
    },
    {
      "nickname": "O",
      "thai_name": "โอ",
      "team": "IT System",
      "total_distance": 126.98,
      "active_days": 19,
      "image_count": 22,
      "recent_images": [
        "../member_results/ITSystem-3_O (โอ)/running-pics/o-2026-mar-08.jpg",
        "../member_results/ITSystem-3_O (โอ)/running-pics/o-2026-mar-04.jpg",
        "../member_results/ITSystem-3_O (โอ)/running-pics/o-2026-mar-03.jpg",
        "../member_results/ITSystem-3_O (โอ)/running-pics/o-2026-jan-31.JPEG",
        "../member_results/ITSystem-3_O (โอ)/running-pics/o-2026-jan-26.JPEG"
      ],
      "stats_details": {
        "run_dist": 144.91,
        "walk_dist": 0.0,
        "run_count": 22,
        "walk_count": 0,
        "total_sessions": 22,
        "best_pace": 436,
        "best_pace_activity": "Outdoor Run",
        "best_pace_date": "2025-12-31",
        "longest_run_dist": 22.4,
        "longest_run_activity": "Half Marathon Race (ฮาล์ฟมาราธอน)",
        "longest_run_date": "2026-03-08"
      }
    },
    {
      "nickname": "Boy",
      "thai_name": "บอย",
      "team": "IT System",
      "total_distance": 111.92,
      "active_days": 18,
      "image_count": 18,
      "recent_images": [
        "../member_results/ITSystem-8_Boy (บอย)/running-pics/boy-2026-mar-08.jpg",
        "../member_results/ITSystem-8_Boy (บอย)/running-pics/boy-2026-mar-07.jpg",
        "../member_results/ITSystem-8_Boy (บอย)/running-pics/boy-2026-mar-04.jpg",
        "../member_results/ITSystem-8_Boy (บอย)/running-pics/boy-2026-jan-29.jpg",
        "../member_results/ITSystem-8_Boy (บอย)/running-pics/boy-2026-jan-28.jpg"
      ],
      "stats_details": {
        "run_dist": 110.82000000000001,
        "walk_dist": 0.0,
        "run_count": 18,
        "walk_count": 0,
        "total_sessions": 18,
        "best_pace": 380,
        "best_pace_activity": "Morning Run",
        "best_pace_date": "2026-02-27",
        "longest_run_dist": 8.0,
        "longest_run_activity": "Morning Run",
        "longest_run_date": "2026-02-27"
      }
    },
    {
      "nickname": "Sand",
      "thai_name": "แซนด์",
      "team": "Mandalorian",
      "total_distance": 62.44,
      "active_days": 19,
      "image_count": 25,
      "recent_images": [
        "../member_results/Manda-5_แซนด์ (SAND)/running-pics/sand-2026-mar-08_1.jpg",
        "../member_results/Manda-5_แซนด์ (SAND)/running-pics/sand-2026-mar-08.jpg",
        "../member_results/Manda-5_แซนด์ (SAND)/running-pics/sand-2026-mar-05.jpg",
        "../member_results/Manda-5_แซนด์ (SAND)/running-pics/sand-2026-mar-04.jpg",
        "../member_results/Manda-5_แซนด์ (SAND)/running-pics/sand-2026-mar-03.jpg"
      ],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 69.82000000000001,
        "run_count": 0,
        "walk_count": 22,
        "total_sessions": 22,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "Oat",
      "thai_name": "โอ๊ต",
      "team": "IT System",
      "total_distance": 58.97,
      "active_days": 11,
      "image_count": 12,
      "recent_images": [
        "../member_results/ITSystem-1_Oat (โอ๊ต)/running-pics/oat-2026-mar-07.jpg",
        "../member_results/ITSystem-1_Oat (โอ๊ต)/running-pics/oat-2026-mar-04.jpg",
        "../member_results/ITSystem-1_Oat (โอ๊ต)/running-pics/oat-2026-mar-03_1.jpg",
        "../member_results/ITSystem-1_Oat (โอ๊ต)/running-pics/oat-2026-mar-03.jpg",
        "../member_results/ITSystem-1_Oat (โอ๊ต)/running-pics/oat-2026-jan-30.jpg"
      ],
      "stats_details": {
        "run_dist": 48.89000000000001,
        "walk_dist": 10.08,
        "run_count": 10,
        "walk_count": 2,
        "total_sessions": 12,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 7.05,
        "longest_run_activity": "Indoor Run (วิ่งในร่ม)",
        "longest_run_date": "2026-02-01"
      }
    },
    {
      "nickname": "Boat",
      "thai_name": "โบ๊ท",
      "team": "Mandalorian",
      "total_distance": 57.42,
      "active_days": 9,
      "image_count": 9,
      "recent_images": [
        "../member_results/Manda-2_โบ๊ท (Boat)/running-pics/boat-2026-mar-07.jpg",
        "../member_results/Manda-2_โบ๊ท (Boat)/running-pics/boat-2026-mar-05.jpg",
        "../member_results/Manda-2_โบ๊ท (Boat)/running-pics/boat-2026-jan-31.JPEG",
        "../member_results/Manda-2_โบ๊ท (Boat)/running-pics/boat-2026-jan-27.jpg",
        "../member_results/Manda-2_โบ๊ท (Boat)/running-pics/boat-2026-jan-24.jpg"
      ],
      "stats_details": {
        "run_dist": 52.739999999999995,
        "walk_dist": 4.68,
        "run_count": 8,
        "walk_count": 1,
        "total_sessions": 9,
        "best_pace": 497,
        "best_pace_activity": "Evening Run (วิ่งเย็น)",
        "best_pace_date": "2026-03-05",
        "longest_run_dist": 8.68,
        "longest_run_activity": "7km Long Run",
        "longest_run_date": "2026-03-07"
      }
    },
    {
      "nickname": "Palm",
      "thai_name": "ปาล์ม",
      "team": "IT System",
      "total_distance": 55.64,
      "active_days": 13,
      "image_count": 13,
      "recent_images": [
        "../member_results/ITSystem-4_Palm (ปาล์ม)/running-pics/palm-2026-mar-08.jpg",
        "../member_results/ITSystem-4_Palm (ปาล์ม)/running-pics/palm-2026-mar-01.jpg",
        "../member_results/ITSystem-4_Palm (ปาล์ม)/running-pics/palm-2026-jan-31.jpg",
        "../member_results/ITSystem-4_Palm (ปาล์ม)/running-pics/palm-2026-jan-29.jpg",
        "../member_results/ITSystem-4_Palm (ปาล์ม)/running-pics/palm-2026-jan-27.jpg"
      ],
      "stats_details": {
        "run_dist": 34.10999999999999,
        "walk_dist": 21.53,
        "run_count": 9,
        "walk_count": 4,
        "total_sessions": 13,
        "best_pace": 668,
        "best_pace_activity": "5km Long Session",
        "best_pace_date": "2026-03-08",
        "longest_run_dist": 5.01,
        "longest_run_activity": "5km Long Session",
        "longest_run_date": "2026-03-08"
      }
    },
    {
      "nickname": "Ton",
      "thai_name": "ต้น",
      "team": "IT System",
      "total_distance": 41.62,
      "active_days": 16,
      "image_count": 24,
      "recent_images": [
        "../member_results/ITSystem-9_Ton (ต้น)/running-pics/ton-2026-jan-30_1.jpg",
        "../member_results/ITSystem-9_Ton (ต้น)/running-pics/ton-2026-jan-30.jpg",
        "../member_results/ITSystem-9_Ton (ต้น)/running-pics/ton-2026-jan-29_1.jpg",
        "../member_results/ITSystem-9_Ton (ต้น)/running-pics/ton-2026-jan-29.jpg",
        "../member_results/ITSystem-9_Ton (ต้น)/running-pics/ton-2026-jan-27_1.jpg"
      ],
      "stats_details": {
        "run_dist": 39.620000000000005,
        "walk_dist": 2.0,
        "run_count": 15,
        "walk_count": 1,
        "total_sessions": 16,
        "best_pace": 484,
        "best_pace_activity": "Morning Run",
        "best_pace_date": "2026-02-01",
        "longest_run_dist": 4.15,
        "longest_run_activity": "Morning Run",
        "longest_run_date": "2026-01-27"
      }
    },
    {
      "nickname": "Chan",
      "thai_name": "พี่ฉันท์",
      "team": "Mandalorian",
      "total_distance": 32.61,
      "active_days": 8,
      "image_count": 11,
      "recent_images": [
        "../member_results/Manda-9_พี่ฉันท์ (Chan)/running-pics/chan-2026-mar-08.jpg",
        "../member_results/Manda-9_พี่ฉันท์ (Chan)/running-pics/chan-2026-mar-04.jpg",
        "../member_results/Manda-9_พี่ฉันท์ (Chan)/running-pics/chan-2026-mar-02.jpg",
        "../member_results/Manda-9_พี่ฉันท์ (Chan)/running-pics/chan-2026-jan-25_1.jpg",
        "../member_results/Manda-9_พี่ฉันท์ (Chan)/running-pics/chan-2026-jan-25.jpg"
      ],
      "stats_details": {
        "run_dist": 7.99,
        "walk_dist": 33.24,
        "run_count": 3,
        "walk_count": 8,
        "total_sessions": 11,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 3.47,
        "longest_run_activity": "Outdoor Running (วิ่งกลางแจ้ง)",
        "longest_run_date": "2026-02-23"
      }
    },
    {
      "nickname": "Em",
      "thai_name": "เอ็ม",
      "team": "Mandalorian",
      "total_distance": 30.37,
      "active_days": 5,
      "image_count": 5,
      "recent_images": [
        "../member_results/Manda-4_เอ็ม (EM)/running-pics/em-2026-mar-08.jpg",
        "../member_results/Manda-4_เอ็ม (EM)/running-pics/em-2026-mar-03.jpg",
        "../member_results/Manda-4_เอ็ม (EM)/running-pics/em-2026-jan-25.JPEG",
        "../member_results/Manda-4_เอ็ม (EM)/running-pics/em-2026-jan-24.JPEG",
        "../member_results/Manda-4_เอ็ม (EM)/running-pics/em-2026-feb-01.JPEG"
      ],
      "stats_details": {
        "run_dist": 30.37,
        "walk_dist": 0.0,
        "run_count": 5,
        "walk_count": 0,
        "total_sessions": 5,
        "best_pace": 500,
        "best_pace_activity": "Outdoor Run (วิ่งกลางแจ้ง)",
        "best_pace_date": "2026-02-01",
        "longest_run_dist": 9.66,
        "longest_run_activity": "Outdoor Run (วิ่งกลางแจ้ง)",
        "longest_run_date": "2026-02-01"
      }
    },
    {
      "nickname": "Toro",
      "thai_name": "ต้อ",
      "team": "Mandalorian",
      "total_distance": 23.04,
      "active_days": 5,
      "image_count": 5,
      "recent_images": [
        "../member_results/Manda-3_ต้อ (TORO)/running-pics/toro-2026-mar-08.jpg",
        "../member_results/Manda-3_ต้อ (TORO)/running-pics/toro-2026-mar-03.jpg",
        "../member_results/Manda-3_ต้อ (TORO)/running-pics/toro-2026-jan-25.JPEG",
        "../member_results/Manda-3_ต้อ (TORO)/running-pics/toro-2026-jan-24.jpg",
        "../member_results/Manda-3_ต้อ (TORO)/running-pics/toro-2026-feb-13.jpg"
      ],
      "stats_details": {
        "run_dist": 23.04,
        "walk_dist": 0.0,
        "run_count": 5,
        "walk_count": 0,
        "total_sessions": 5,
        "best_pace": 389,
        "best_pace_activity": "Evening Run (วิ่งตอนเย็น)",
        "best_pace_date": "2026-02-13",
        "longest_run_dist": 5.52,
        "longest_run_activity": "5.5km Long Run",
        "longest_run_date": "2026-03-08"
      }
    },
    {
      "nickname": "Game",
      "thai_name": "เกมส์",
      "team": "IT System",
      "total_distance": 22.63,
      "active_days": 4,
      "image_count": 8,
      "recent_images": [
        "../member_results/ITSystem-2_Game (เกมส์)/running-pics/game-2026-jan-27.JPEG",
        "../member_results/ITSystem-2_Game (เกมส์)/running-pics/game-2026-jan-21.JPEG",
        "../member_results/ITSystem-2_Game (เกมส์)/running-pics/game-2026-jan-19.JPEG",
        "../member_results/ITSystem-2_Game (เกมส์)/running-pics/game-2026-jan-05.png",
        "../member_results/ITSystem-2_Game (เกมส์)/running-pics/game-2025-dec-30_2.png"
      ],
      "stats_details": {
        "run_dist": 44.89,
        "walk_dist": 0.0,
        "run_count": 6,
        "walk_count": 0,
        "total_sessions": 6,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 11.13,
        "longest_run_activity": "Indoor Run (วิ่งในร่ม)",
        "longest_run_date": "2025-12-29"
      }
    },
    {
      "nickname": "Mos",
      "thai_name": "มอส",
      "team": "Mandalorian",
      "total_distance": 20.74,
      "active_days": 7,
      "image_count": 7,
      "recent_images": [
        "../member_results/Manda-10_มอส (Mos)/running-pics/mos-2026-mar-03.jpg",
        "../member_results/Manda-10_มอส (Mos)/running-pics/mos-2026-mar-01.jpg",
        "../member_results/Manda-10_มอส (Mos)/running-pics/mos-2026-jan-21.jpg",
        "../member_results/Manda-10_มอส (Mos)/running-pics/mos-2026-jan-20.jpg",
        "../member_results/Manda-10_มอส (Mos)/running-pics/mos-2026-jan-19.jpg"
      ],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 20.74,
        "run_count": 0,
        "walk_count": 7,
        "total_sessions": 7,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "Oum",
      "thai_name": "อุ้ม",
      "team": "IT System",
      "total_distance": 16.7,
      "active_days": 4,
      "image_count": 5,
      "recent_images": [
        "../member_results/ITSystem-5_Oum (อุ้ม)/running-pics/oum-2026-jan-21.jpg",
        "../member_results/ITSystem-5_Oum (อุ้ม)/running-pics/oum-2026-jan-18_1.jpg",
        "../member_results/ITSystem-5_Oum (อุ้ม)/running-pics/oum-2026-jan-18.jpg",
        "../member_results/ITSystem-5_Oum (อุ้ม)/running-pics/oum-2026-jan-14.png",
        "../member_results/ITSystem-5_Oum (อุ้ม)/running-pics/oum-2026-feb-19.jpg"
      ],
      "stats_details": {
        "run_dist": 11.489999999999998,
        "walk_dist": 5.21,
        "run_count": 4,
        "walk_count": 1,
        "total_sessions": 5,
        "best_pace": 480,
        "best_pace_activity": "การวิ่ง (Outdoor Run)",
        "best_pace_date": "2026-01-18",
        "longest_run_dist": 3.78,
        "longest_run_activity": "การวิ่ง (Outdoor Run)",
        "longest_run_date": "2026-01-18"
      }
    },
    {
      "nickname": "Fuse",
      "thai_name": "ฟิวส์",
      "team": "Mandalorian",
      "total_distance": 12.76,
      "active_days": 1,
      "image_count": 1,
      "recent_images": [
        "../member_results/Manda-8_ฟิวส์ (fuse)/running-pics/fuse-2026-jan-24.JPEG"
      ],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 12.76,
        "run_count": 0,
        "walk_count": 1,
        "total_sessions": 1,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "PAN",
      "thai_name": "แพน",
      "team": "IT System",
      "total_distance": 4.21,
      "active_days": 2,
      "image_count": 2,
      "recent_images": [
        "../member_results/ITSystem-10_PAN (แพน)/running-pics/pan-2026-feb-08.JPG",
        "../member_results/ITSystem-10_PAN (แพน)/running-pics/pan-2026-feb-07.JPG"
      ],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 4.21,
        "run_count": 0,
        "walk_count": 2,
        "total_sessions": 2,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "Peck",
      "thai_name": "เป๊ก",
      "team": "Mandalorian",
      "total_distance": 0.0,
      "active_days": 0,
      "image_count": 0,
      "recent_images": [],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 0.0,
        "run_count": 0,
        "walk_count": 0,
        "total_sessions": 0,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "Neung",
      "thai_name": "หนึ่ง",
      "team": "Mandalorian",
      "total_distance": 0.0,
      "active_days": 0,
      "image_count": 0,
      "recent_images": [],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 0.0,
        "run_count": 0,
        "walk_count": 0,
        "total_sessions": 0,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    },
    {
      "nickname": "Tae",
      "thai_name": "เต",
      "team": "IT System",
      "total_distance": 0.0,
      "active_days": 0,
      "image_count": 0,
      "recent_images": [],
      "stats_details": {
        "run_dist": 0.0,
        "walk_dist": 0.0,
        "run_count": 0,
        "walk_count": 0,
        "total_sessions": 0,
        "best_pace": null,
        "best_pace_activity": "",
        "best_pace_date": "",
        "longest_run_dist": 0.0,
        "longest_run_activity": "",
        "longest_run_date": ""
      }
    }
  ],
  "recent_activities": [
    {
      "date": "2026-03-09",
      "name": "GIO",
      "distance": 5.57,
      "month": "2026-March"
    },
    {
      "date": "2026-03-09",
      "name": "GIO",
      "distance": 3.83,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Sand",
      "distance": 7.12,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Sand",
      "distance": 2.86,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Toro",
      "distance": 5.52,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "EM",
      "distance": 7.16,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Chan",
      "distance": 5.47,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Boy",
      "distance": 7.08,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "O",
      "distance": 22.4,
      "month": "2026-March"
    },
    {
      "date": "2026-03-08",
      "name": "Palm",
      "distance": 5.01,
      "month": "2026-March"
    },
    {
      "date": "2026-03-07",
      "name": "GIO",
      "distance": 10.03,
      "month": "2026-March"
    },
    {
      "date": "2026-03-07",
      "name": "GIO",
      "distance": 6.65,
      "month": "2026-March"
    },
    {
      "date": "2026-03-07",
      "name": "Boat",
      "distance": 8.68,
      "month": "2026-March"
    },
    {
      "date": "2026-03-07",
      "name": "Boy",
      "distance": 7.0,
      "month": "2026-March"
    },
    {
      "date": "2026-03-07",
      "name": "Oat",
      "distance": 5.04,
      "month": "2026-March"
    },
    {
      "date": "2026-03-05",
      "name": "GIO",
      "distance": 5.7,
      "month": "2026-March"
    },
    {
      "date": "2026-03-05",
      "name": "GIO",
      "distance": 8.36,
      "month": "2026-March"
    },
    {
      "date": "2026-03-05",
      "name": "Boat",
      "distance": 5.08,
      "month": "2026-March"
    },
    {
      "date": "2026-03-05",
      "name": "Sand",
      "distance": 2.56,
      "month": "2026-March"
    },
    {
      "date": "2026-03-05",
      "name": "Jojo",
      "distance": 10.01,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "Sand",
      "distance": 2.07,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "Chan",
      "distance": 4.94,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "Oat",
      "distance": 5.06,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "Jojo",
      "distance": 2.34,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "O",
      "distance": 6.01,
      "month": "2026-March"
    },
    {
      "date": "2026-03-04",
      "name": "Boy",
      "distance": 5.38,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "GIO",
      "distance": 7.92,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "GIO",
      "distance": 4.37,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "Toro",
      "distance": 4.52,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "EM",
      "distance": 5.15,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "Sand",
      "distance": 7.27,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "Mos",
      "distance": 2.95,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "Oat",
      "distance": 5.1,
      "month": "2026-March"
    },
    {
      "date": "2026-03-03",
      "name": "O",
      "distance": 6.0,
      "month": "2026-March"
    },
    {
      "date": "2026-03-02",
      "name": "GIO",
      "distance": 9.47,
      "month": "2026-March"
    },
    {
      "date": "2026-03-02",
      "name": "Chan",
      "distance": 2.53,
      "month": "2026-March"
    },
    {
      "date": "2026-03-02",
      "name": "Sand",
      "distance": 2.24,
      "month": "2026-March"
    },
    {
      "date": "2026-03-02",
      "name": "Jojo",
      "distance": 10.01,
      "month": "2026-March"
    },
    {
      "date": "2026-03-01",
      "name": "Mos",
      "distance": 2.24,
      "month": "2026-March"
    },
    {
      "date": "2026-03-01",
      "name": "Palm",
      "distance": 6.01,
      "month": "2026-March"
    },
    {
      "date": "2026-03-01",
      "name": "Jojo",
      "distance": 4.7,
      "month": "2026-March"
    },
    {
      "date": "2026-02-28",
      "name": "GIO",
      "distance": 4.12,
      "month": "2026-February"
    },
    {
      "date": "2026-02-28",
      "name": "GIO",
      "distance": 10.06,
      "month": "2026-February"
    },
    {
      "date": "2026-02-28",
      "name": "Sand",
      "distance": 2.32,
      "month": "2026-February"
    },
    {
      "date": "2026-02-28",
      "name": "Boat",
      "distance": 6.83,
      "month": "2026-February"
    },
    {
      "date": "2026-02-28",
      "name": "O",
      "distance": 6.01,
      "month": "2026-February"
    },
    {
      "date": "2026-02-28",
      "name": "Palm",
      "distance": 5.5,
      "month": "2026-February"
    },
    {
      "date": "2026-02-27",
      "name": "Jojo",
      "distance": 10.01,
      "month": "2026-February"
    },
    {
      "date": "2026-02-27",
      "name": "Boy",
      "distance": 8.0,
      "month": "2026-February"
    },
    {
      "date": "2026-02-26",
      "name": "GIO",
      "distance": 3.47,
      "month": "2026-February"
    }
  ]
};
