import os
import re
import json
import shutil
from pathlib import Path

def sanitize_name(name):
    """
    Remove any Thai characters and special symbols, keeping only A-Z, a-z, 0-9, -, _, and .
    """
    # Remove all characters that are not English alphanumeric, dash, underscore, or dot
    sanitized = re.sub(r'[^A-Za-z0-9_\-\.]', '', name)
    # Give it a generic name if it ended up completely empty
    if not sanitized:
        sanitized = "asset"
    return sanitized

def main():
    base_dir = Path(__file__).parent.parent.absolute()
    html_data_js = base_dir / 'html' / 'data.js'
    
    react_public = base_dir / 'webapp-react' / 'public'
    assets_out_dir = react_public / 'assets_data'
    
    # 1. Clear out the old assets_data directory
    if assets_out_dir.exists():
        shutil.rmtree(assets_out_dir)
    assets_out_dir.mkdir(parents=True, exist_ok=True)
    
    # 2. Read existing data.js and parse as JSON
    print("Reading html/data.js...")
    with open(html_data_js, 'r', encoding='utf-8') as f:
        content = f.read()

    # The file starts with something like:
    # // Auto-generated by build_website_data.py
    # window.COMPETITION_DATA = { ... }
    
    # Find the first '{' and parse until the end (ignoring trailing semicolons if any)
    json_start = content.find('{')
    json_end = content.rfind('}')
    
    if json_start == -1 or json_end == -1:
        print("Error: Could not find valid JSON object in data.js")
        return
        
    json_str = content[json_start:json_end+1]
    
    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON from data.js: {e}")
        return

    # Helper function to copy and sanitize file path
    # Returns the relative Path for the React application to use
    def copy_file_to_assets(src_str):
        if not src_str:
            return ""
        
        # Paths in data.js typically look like "../member_results/Manda-1_โจ (GIO)/running-pics/gio-2026-mar-09_1.jpg"
        # Since this script runs from the project root (or paths are relative to html/), let's resolve them
        # Actually, let's treat the path relative to html/ directory because that's where data.js lived.
        src_path = (base_dir / 'html' / src_str).resolve()
        
        if not src_path.exists():
            return src_str # Return original if we cannot resolve it

        # Build sanitized destination hierarchy
        # We'll put everything under /assets_data/ preserving some of the folder structure but sanitized
        # Let's say we preserve the last 3 parts: member_results / {member} / running-pics / {file}
        parts = src_path.parts[-4:]
        
        sanitized_parts = [sanitize_name(p) for p in parts]
        dest_rel = Path(*sanitized_parts)
        dest_full = assets_out_dir / dest_rel
        
        dest_full.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_full)
        
        # React will access this as exactly '/assets_data/...' 
        # (Assuming React router basename handles the prefix, we can just return relative to public root)
        return str(Path('/assets_data') / dest_rel).replace('\\', '/')

    print("Sanitizing and copying assets...")

    # 3. Traverse the parsed data and update image paths
    for member in data.get('roster', []):
        # Update recent_images
        new_recent_images = []
        for img in member.get('recent_images', []):
            new_recent_images.append(copy_file_to_assets(img))
        member['recent_images'] = new_recent_images

        # If data has markdown images inside the markdown text...
        # We might need to do regex replacement on markdown text itself, but let's see if that's required.
        # Actually, the user asked to "copy_file_to_assets(md)". 
        # Let's do a regex replace over all member['markdown']['readme'] and ['statistics'] and ['plan']
        
        def replace_md_links(match):
            original_path = "../" + match.group(1)
            new_path = copy_file_to_assets(original_path)
            # The regex matched "](../something)", so we need to return "](" + new_path + ")"
            return f"]({new_path})"

        md_dict = member.get('markdown', {})
        for key in md_dict:
            # Matches strings like: ](../member_results/Manda-1_โจ (GIO)/running-pics/gio.jpg)
            # The regex looks for ]( followed by relative path starting with ../
            md_dict[key] = re.sub(r'\]\(\.\./([^)]+)\)', replace_md_links, md_dict[key])
            
    # Also traverse activities for daily runner images
    for act in data.get('activities', []):
        for runner in act.get('runners_list', []):
            new_images = []
            for img in runner.get('images', []):
                new_images.append(copy_file_to_assets(img))
            runner['images'] = new_images

    # 4. Save data.json strictly
    out_json = react_public / 'data.json'
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ Successfully wrote data.json to {out_json}")
    
    # 5. Copy the main results and README globally, if needed
    readme_src = base_dir / 'README.md'
    if readme_src.exists():
        shutil.copy2(readme_src, assets_out_dir / 'README.md')
        
    results_dir_src = base_dir / 'results'
    if results_dir_src.exists():
        for f in results_dir_src.glob('*.md'):
            # Only English characters
            dest_name = sanitize_name(f.name)
            shutil.copy2(f, assets_out_dir / dest_name)
    
    print("Asset build complete.")

if __name__ == "__main__":
    main()
